name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: write

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish
        run: npx electron-builder --publish always